version: '3'

services:
  nim-dev:
    build:
      context: .
      dockerfile: ./vscode.dockerfile
    image: nim-dev:1.6.2

  selenium-hub:
    image: selenium/hub:3.141.59-20210830
    environment:
      - GRID_MAX_SESSION=10

  chrome:
    image: selenium/node-chrome:3.141.59-20210830
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_SESSION=5
